apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    name: stateful-app
    app: mysql

spec:
  serviceName: mysql-h
  replicas: 3
  selector:
    matchLabels:
      app: stateful-app
  template:
    metadata:
      name: myapp-pod
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql
