apiVersion: v1
kind: Service
metadata:
  name: webapp-color-service
  uid: 94f60ce7-bc0c-4a8c-9f5d-cc055348f2cd
spec:
  clusterIP: 10.103.207.187
  clusterIPs:
  - 10.103.207.187
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    name: webapp-color
  sessionAffinity: None
  type: NodePort